language: go
sudo: required

os:
  - linux
  - osx

go:
  - tip
  - 1.13.x
  - 1.12.x
  - 1.11.x

matrix:
  allow_failures:
    - go: tip

before_install:
  - export GOFLAGS=-mod=vendor
  - if [ $TRAVIS_OS_NAME = "linux" ]; then sudo apt-get -qq update; sudo apt-get install -y dwz; echo "dwz version $(dwz --version)"; fi
  
